# Generated by Django 3.2.7 on 2021-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsKerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addres', models.GenericIPAddressField(verbose_name='IP')),
                ('user_name', models.CharField(max_length=200, verbose_name='Usuario')),
                ('date_time', models.DateTimeField(verbose_name='Fecha')),
                ('time_zone', models.CharField(max_length=100, verbose_name='Zona horario')),
                ('http_method', models.CharField(max_length=50, verbose_name='Metodo http')),
                ('url', models.CharField(max_length=10000, verbose_name='Url')),
                ('version_http', models.CharField(max_length=50, verbose_name='Version de http')),
                ('code_http', models.CharField(max_length=200, verbose_name='Codigo http')),
                ('size_transfered', models.IntegerField(verbose_name='Tamanno de transf')),
                ('count_requests_transferred', models.CharField(max_length=1000, verbose_name='Cant de transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='LogsSquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Fecha')),
                ('time_request', models.IntegerField(verbose_name='Duracion de consulta')),
                ('ip_client', models.GenericIPAddressField(verbose_name='Ip cliente')),
                ('cache_result_code', models.CharField(max_length=50, verbose_name='Codigo de cache')),
                ('size_transfered', models.IntegerField(verbose_name='Tamanno de transf')),
                ('http_method', models.CharField(max_length=50, verbose_name='Metodo http')),
                ('url', models.CharField(max_length=10000, verbose_name='Url')),
                ('user_name', models.CharField(max_length=200, verbose_name='Usuario')),
                ('request_server_name', models.CharField(max_length=200, verbose_name='Nombre servidor')),
                ('content_type', models.CharField(max_length=100, verbose_name='Tipo de contenido')),
            ],
        ),
    ]
