# Generated by Django 3.2.7 on 2021-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logssquid',
            name='time_stamp',
            field=models.CharField(default=1627704012, max_length=100, verbose_name='Time Stamp'),
        ),
    ]
