# Generated by Django 3.2.7 on 2022-09-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logskerio',
            name='ip_addres',
            field=models.BigIntegerField(verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='logssquid',
            name='time_request',
            field=models.BigIntegerField(verbose_name='Duracion de consulta'),
        ),
    ]
