# Generated by Django 3.2.7 on 2021-11-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0002_logssquid_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(verbose_name='Fecha entrada')),
                ('domain', models.CharField(max_length=1000, verbose_name='Dominio')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
    ]
