# Generated by Django 3.2.7 on 2022-09-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0002_auto_20220909_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logskerio',
            name='ip_addres',
            field=models.PositiveBigIntegerField(verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='logssquid',
            name='ip_client',
            field=models.PositiveBigIntegerField(verbose_name='Ip cliente'),
        ),
    ]
