# Generated by Django 3.2.7 on 2021-11-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0003_blacklistdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('typeEntity', models.CharField(max_length=200, verbose_name='Clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cell', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastName1', models.CharField(max_length=200, verbose_name='Primer Apellido')),
                ('lastName2', models.CharField(max_length=200, verbose_name='Primer Apellido')),
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('planeData', models.IntegerField()),
                ('serviceTypeMail', models.CharField(choices=[('nac', 'nacional'), ('int', 'Internancional'), ('cor', 'correo')], default='Nacional', max_length=15, verbose_name='Tipo de servicio Mail')),
                ('serviceTypeNavPC', models.CharField(choices=[('nac', 'nacional'), ('int', 'Internancional'), ('cor', 'correo')], default='Nacional', max_length=15, verbose_name='Tipo de servicio Nav PC')),
                ('serviceTypeNavCell', models.CharField(choices=[('nac', 'nacional'), ('int', 'Internancional'), ('cor', 'correo')], default='Nacional', max_length=15, verbose_name='Tipo de servicio Nav Cell')),
                ('socialNetwork', models.CharField(max_length=2000, verbose_name='Red social')),
                ('root', models.BooleanField(default=False, verbose_name='Permiso Admin')),
                ('quickAnswer', models.BooleanField(default=False, verbose_name='Grup. Respueta Rapida')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_squid_kerio.entity')),
            ],
        ),
    ]
