# Generated by Django 3.2.7 on 2022-12-08 15:39

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0003_auto_20220909_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logssquid',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='logssquid',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
