# Generated by Django 3.2.7 on 2022-12-08 16:14

from django.db import migrations, models
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0004_auto_20221208_1539'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='LogsSquidPartitioned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(default=1627704012, max_length=100, verbose_name='Time Stamp')),
                ('date_time', models.DateTimeField(verbose_name='Fecha')),
                ('time_request', models.BigIntegerField(verbose_name='Duracion de consulta')),
                ('ip_client', models.PositiveBigIntegerField(verbose_name='Ip cliente')),
                ('cache_result_code', models.CharField(max_length=50, verbose_name='Codigo de cache')),
                ('size_transfered', models.IntegerField(verbose_name='Tamanno de transf')),
                ('http_method', models.CharField(max_length=50, verbose_name='Metodo http')),
                ('url', models.CharField(max_length=10000, verbose_name='Url')),
                ('user_name', models.CharField(max_length=200, verbose_name='Usuario')),
                ('request_server_name', models.CharField(max_length=200, verbose_name='Nombre servidor')),
                ('content_type', models.CharField(max_length=100, verbose_name='Tipo de contenido')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['RANGE'],
                'key': ['date_time'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='LogsSquidPartitioned',
            name='default',
        ),
        migrations.AlterModelOptions(
            name='logssquid',
            options={},
        ),
        migrations.AlterModelManagers(
            name='logssquid',
            managers=[
            ],
        ),
    ]
