# Generated by Django 3.2.7 on 2021-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0004_entity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliceTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(verbose_name='Slice inicio')),
                ('end', models.IntegerField(verbose_name='Slice fin')),
                ('step', models.IntegerField(verbose_name='Slice paso')),
                ('multiplier', models.IntegerField(verbose_name='Multiplicador ')),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='typeEntity',
            field=models.CharField(choices=[('UEB', 'UEB'), ('Dir', 'Direccion')], default='UEB', max_length=10, verbose_name='Clasificacion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName2',
            field=models.CharField(max_length=200, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='planeData',
            field=models.IntegerField(verbose_name='Plan de Datos (MB)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceTypeMail',
            field=models.CharField(choices=[('nac', 'Nacional'), ('int', 'Internancional')], default='nac', max_length=15, verbose_name='Tipo de servicio Mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceTypeNavCell',
            field=models.CharField(choices=[('int', 'Internancional'), ('cor', 'correo')], default='int', max_length=15, verbose_name='Tipo de servicio Nav Cell'),
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceTypeNavPC',
            field=models.CharField(choices=[('nac', 'Nacional'), ('int', 'Internancional')], default='nac', max_length=15, verbose_name='Tipo de servicio Nav PC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='socialNetwork',
            field=models.CharField(default='Ninguno', max_length=2000, verbose_name='Red social'),
        ),
    ]
