# Generated by Django 3.2.7 on 2022-12-08 17:28

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddRangePartition


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0005_auto_20221208_1614'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="LogsSquidPartitioned",
            name="logsquid_20220901_20220906",
            from_values="2022-09-01",
            to_values="2022-09-06",
        ),
    ]
