# Generated by Django 3.2.7 on 2021-12-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0005_auto_20211215_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slicetmp',
            old_name='star',
            new_name='start',
        ),
    ]
