# Generated by Django 3.2.7 on 2022-01-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0006_rename_star_slicetmp_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlackListDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='blacklistdomain',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_squid_kerio.categoryblacklistdomain'),
        ),
    ]
