# Generated by Django 3.2.7 on 2022-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0007_auto_20220111_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsSquidTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(default=1627704012, max_length=100, verbose_name='Time Stamp')),
                ('date_time', models.DateTimeField(verbose_name='Fecha')),
                ('time_request', models.IntegerField(verbose_name='Duracion de consulta')),
                ('ip_client', models.GenericIPAddressField(verbose_name='Ip cliente')),
                ('cache_result_code', models.CharField(max_length=50, verbose_name='Codigo de cache')),
                ('size_transfered', models.IntegerField(verbose_name='Tamanno de transf')),
                ('http_method', models.CharField(max_length=50, verbose_name='Metodo http')),
                ('url', models.CharField(max_length=10000, verbose_name='Url')),
                ('user_name', models.CharField(max_length=200, verbose_name='Usuario')),
                ('request_server_name', models.CharField(max_length=200, verbose_name='Nombre servidor')),
                ('content_type', models.CharField(max_length=100, verbose_name='Tipo de contenido')),
            ],
        ),
    ]
