# Generated by Django 3.2.7 on 2022-12-08 21:17

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddRangePartition


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0015_auto_20221208_2109'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="LogsSquidPartitioned",
            name="logsquid_20221116_20221121",
            from_values="2022-11-16",
            to_values="2022-11-21",
        ),
    ]
