# Generated by Django 3.2.7 on 2023-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_squid_kerio', '0019_auto_20221208_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
